import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

interface GoMirror {
  readonly package: string;
  readonly version: string;
}

interface Family {
  readonly id: string;
  readonly generator: string;
  readonly tsconfig: string;
  readonly goMirror?: GoMirror;
}

interface Registry {
  readonly schema: 'openslack.workflow_contract_family_registry.v1';
  readonly families: readonly Family[];
}

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const registryPath = resolve(repositoryRoot, 'scripts/workflow-contract-families.json');
const shellInventoryPath = resolve(
  repositoryRoot,
  'scripts/workflow-contract-families.generated.sh',
);
const dockerignorePath = resolve(repositoryRoot, 'services/workflow-control/.dockerignore');
const beginMarker = '# BEGIN GENERATED WORKFLOW CONTRACT FAMILIES';
const endMarker = '# END GENERATED WORKFLOW CONTRACT FAMILIES';

function registry(): Registry {
  const value = JSON.parse(readFileSync(registryPath, 'utf8')) as Registry;
  if (value.schema !== 'openslack.workflow_contract_family_registry.v1') {
    throw new Error('Workflow contract family registry schema is invalid.');
  }
  if (!Array.isArray(value.families) || value.families.length === 0) {
    throw new Error('Workflow contract family registry is empty.');
  }
  const ids = new Set<string>();
  for (const family of value.families) {
    if (
      !/^[a-z][a-z0-9-]*$/u.test(family.id) ||
      ids.has(family.id) ||
      !family.generator.startsWith('scripts/workflow-') ||
      !family.generator.endsWith('-contracts/index.ts') ||
      family.tsconfig !== family.generator.replace(/index\.ts$/u, 'tsconfig.json')
    ) {
      throw new Error(`Workflow contract family entry is invalid: ${family.id}.`);
    }
    ids.add(family.id);
    if (
      family.goMirror &&
      (!/^[a-z][a-z0-9]*contract$/u.test(family.goMirror.package) ||
        !/^v[1-9][0-9]*$/u.test(family.goMirror.version))
    ) {
      throw new Error(`Workflow contract Go mirror is invalid: ${family.id}.`);
    }
    if (
      family.goMirror &&
      !existsSync(resolve(repositoryRoot, 'services/workflow-control', family.goMirror.package))
    ) {
      throw new Error(`Workflow contract Go mirror package is missing: ${family.id}.`);
    }
  }
  return value;
}

function dockerRules(value: Registry): string[] {
  return value.families.flatMap((family) => {
    const mirror = family.goMirror;
    if (!mirror) return [];
    return [
      `!${mirror.package}/`,
      `!${mirror.package}/*.go`,
      `!${mirror.package}/generated/`,
      `!${mirror.package}/generated/${mirror.version}/`,
      `!${mirror.package}/generated/${mirror.version}/*.json`,
      `!${mirror.package}/generated/${mirror.version}/schemas/`,
      `!${mirror.package}/generated/${mirror.version}/schemas/*.json`,
    ];
  });
}

function shellInventory(value: Registry): string {
  const mirrors = value.families.flatMap((family) => (family.goMirror ? [family.goMirror] : []));
  const rules = dockerRules(value);
  const cases = rules.map((rule) => `    '${rule}') return 0 ;;`).join('\n');
  return `# Generated by scripts/workflow-contract-families/index.ts. Do not edit.\nreadonly -a WORKFLOW_CONTRACT_GO_PACKAGES=(\n${mirrors.map((mirror) => `  '${mirror.package}'`).join('\n')}\n)\n\nworkflow_contract_dockerignore_rule_allowed() {\n  case "$1" in\n${cases}\n    *) return 1 ;;\n  esac\n}\n`;
}

function dockerignore(value: Registry): string {
  const current = readFileSync(dockerignorePath, 'utf8');
  const block = `${beginMarker}\n${dockerRules(value).join('\n')}\n${endMarker}`;
  if (current.includes(beginMarker) !== current.includes(endMarker)) {
    throw new Error('Workflow Control .dockerignore marker block is incomplete.');
  }
  if (current.includes(beginMarker)) {
    const pattern = new RegExp(
      `${escapeRegExp(beginMarker)}[\\s\\S]*?${escapeRegExp(endMarker)}`,
      'u',
    );
    return current.replace(pattern, block);
  }
  const anchor = '!internal/**/*.go';
  if (!current.includes(anchor)) {
    throw new Error('Workflow Control .dockerignore insertion anchor is missing.');
  }
  return current.replace(anchor, `${anchor}\n${block}`);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&');
}

function run(command: string, args: string[]): void {
  const result = spawnSync(command, args, {
    cwd: repositoryRoot,
    encoding: 'utf8',
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
  if (result.status !== 0) {
    throw new Error(`Workflow contract command failed: ${command} ${args.join(' ')}`);
  }
}

function verifyGenerated(value: Registry): void {
  if (readFileSync(shellInventoryPath, 'utf8') !== shellInventory(value)) {
    throw new Error('Workflow contract shell inventory is stale; run --generate-inventory.');
  }
  if (readFileSync(dockerignorePath, 'utf8') !== dockerignore(value)) {
    throw new Error(
      'Workflow Control .dockerignore contract marker is stale; run --generate-inventory.',
    );
  }
}

const value = registry();
const command = process.argv[2] ?? '--check';
switch (command) {
  case '--generate-inventory':
    writeFileSync(shellInventoryPath, shellInventory(value), 'utf8');
    writeFileSync(dockerignorePath, dockerignore(value), 'utf8');
    break;
  case '--typecheck':
    verifyGenerated(value);
    for (const family of value.families)
      run('bun', ['x', 'tsc', '--noEmit', '-p', family.tsconfig]);
    break;
  case '--check':
    verifyGenerated(value);
    for (const family of value.families) run('bun', [family.generator, '--check']);
    break;
  default:
    throw new Error('Usage: index.ts [--generate-inventory|--typecheck|--check]');
}
