import { describe, it, expect } from 'vitest';
import { generateReviewReport } from '../report.js';
import type { PRReviewReport } from '../types.js';

function makeReport(overrides: Partial<PRReviewReport> = {}): PRReviewReport {
  return {
    prNumber: 10,
    title: 'Test PR',
    author: 'test-agent',
    state: 'open',
    draft: false,
    baseRef: 'main',
    riskZone: 'green',
    changedFiles: ['docs/readme.md'],
    checks: [{ name: 'canary', status: 'completed', conclusion: 'success' }],
    reviews: [],
    humanApprovals: [],
    decision: 'READY_TO_MERGE',
    reason: 'All checks passed.',
    recommendation: 'Safe to merge.',
    mergeable: true,
    ...overrides,
  };
}

describe('generateReviewReport', () => {
  it('includes PR number and title', () => {
    const md = generateReviewReport(makeReport());
    expect(md).toContain('#10');
    expect(md).toContain('Test PR');
  });

  it('includes risk zone', () => {
    const md = generateReviewReport(makeReport({ riskZone: 'red' }));
    expect(md).toContain('RED');
  });

  it('includes decision', () => {
    const md = generateReviewReport(makeReport({ decision: 'NEEDS_HUMAN_APPROVAL' }));
    expect(md).toContain('NEEDS_HUMAN_APPROVAL');
  });

  it('includes changed files', () => {
    const md = generateReviewReport(makeReport({ changedFiles: ['a.ts', 'b.ts'] }));
    expect(md).toContain('a.ts');
    expect(md).toContain('b.ts');
  });

  it('includes check status', () => {
    const md = generateReviewReport(makeReport({
      checks: [
        { name: 'classify', status: 'completed', conclusion: 'success' },
        { name: 'canary', status: 'completed', conclusion: 'failure' },
      ],
    }));
    expect(md).toContain('classify');
    expect(md).toContain('canary');
  });

  it('includes human approvals', () => {
    const md = generateReviewReport(makeReport({
      humanApprovals: [{ user: 'wsman' }],
    }));
    expect(md).toContain('@wsman');
  });

  it('contains reason and recommendation', () => {
    const md = generateReviewReport(makeReport({
      reason: 'Test reason',
      recommendation: 'Test recommendation',
    }));
    expect(md).toContain('Test reason');
    expect(md).toContain('Test recommendation');
  });

  it('marks generated by OpenSlack', () => {
    const md = generateReviewReport(makeReport());
    expect(md).toContain('OpenSlack PR Review');
  });
});
