// Code generated by scripts/workflow-recovery-contracts/index.ts; DO NOT EDIT.
package runnerstore

// RecoverySchemasJSON mirrors the explicit TS recovery wire rules.
const RecoverySchemasJSON = `{
  "BindingReconciliationRequest": {
    "type": "object",
    "additionalProperties": false,
    "unevaluatedProperties": false,
    "required": [
      "schema",
      "workspaceId",
      "runId",
      "bindingId",
      "stageHash",
      "outcome",
      "rulesVersion"
    ],
    "properties": {
      "schema": { "const": "openslack.workflow_runner_binding_reconciliation.v1" },
      "workspaceId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "runId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "bindingId": { "type": "string", "pattern": "^WFRUNNER-BINDING-[0-9a-f]{64}$" },
      "stageHash": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
      "outcome": { "enum": ["committed", "not_committed"] },
      "rulesVersion": { "const": 1 }
    }
  },
  "BindingSettlementReceipt": {
    "type": "object",
    "additionalProperties": false,
    "unevaluatedProperties": false,
    "required": [
      "schema",
      "workspaceId",
      "runId",
      "bindingId",
      "stageHash",
      "outcome",
      "proofKind",
      "proof",
      "idempotencyKey",
      "requestHash",
      "callerId",
      "rulesVersion",
      "committedAt"
    ],
    "properties": {
      "schema": { "const": "openslack.workflow_runner_binding_settlement_receipt.v1" },
      "workspaceId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "runId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "bindingId": { "type": "string", "pattern": "^WFRUNNER-BINDING-[0-9a-f]{64}$" },
      "stageHash": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
      "outcome": { "enum": ["committed", "not_committed"] },
      "proofKind": {
        "enum": ["resolution", "source_receipt", "source_fence", "budget_source_result"]
      },
      "proof": { "type": "string", "minLength": 1 },
      "idempotencyKey": {
        "type": "string",
        "pattern": "^openslack\\.workflow-runner-reconciliation\\.v1\\.[0-9a-f]{64}$"
      },
      "requestHash": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
      "callerId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "rulesVersion": { "const": 1 },
      "committedAt": {
        "type": "string",
        "format": "date-time",
        "pattern": "^\\d{4}-\\d\\d-\\d\\dT\\d\\d:\\d\\d:\\d\\d\\.\\d{3}Z$"
      }
    },
    "oneOf": [
      {
        "properties": {
          "outcome": { "const": "not_committed" },
          "proofKind": { "const": "source_fence" }
        }
      },
      {
        "properties": {
          "outcome": { "const": "committed" },
          "proofKind": { "enum": ["resolution", "source_receipt", "budget_source_result"] }
        }
      }
    ]
  },
  "BindingReconciliationPreview": {
    "type": "object",
    "additionalProperties": false,
    "unevaluatedProperties": false,
    "required": ["schema", "workspaceId", "runId", "items", "nextCursor"],
    "properties": {
      "schema": { "const": "openslack.workflow_runner_binding_reconciliation_preview.v1" },
      "workspaceId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "runId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "items": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "unevaluatedProperties": false,
          "required": ["bindingId", "stageHash", "outcome", "code", "proofKind", "receipt"],
          "properties": {
            "bindingId": { "type": "string", "pattern": "^WFRUNNER-BINDING-[0-9a-f]{64}$" },
            "stageHash": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
            "outcome": { "enum": ["committed", "not_committed", "unknown"] },
            "code": {
              "enum": [
                "WORKFLOW_RUNNER_BINDING_SETTLED",
                "WORKFLOW_RUNNER_BINDING_RECONCILABLE",
                "WORKFLOW_RUNNER_RECONCILIATION_REQUIRED"
              ]
            },
            "proofKind": {
              "enum": ["", "resolution", "source_receipt", "source_fence", "budget_source_result"]
            },
            "receipt": { "type": ["string", "null"], "minLength": 1 }
          }
        }
      },
      "nextCursor": { "type": ["string", "null"], "pattern": "^WFRUNNER-BINDING-[0-9a-f]{64}$" }
    }
  },
  "RecoveryEvidenceV2": {
    "type": "object",
    "additionalProperties": false,
    "unevaluatedProperties": false,
    "required": [
      "schema",
      "workspaceId",
      "runId",
      "route",
      "complete",
      "snapshot",
      "nextCursor",
      "records"
    ],
    "properties": {
      "schema": { "const": "openslack.workflow_runner_recovery_evidence.v2" },
      "workspaceId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "runId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "route": {
        "type": "object",
        "additionalProperties": false,
        "unevaluatedProperties": false,
        "required": ["backend", "authority", "routingEpoch", "authorityBuildHash"],
        "properties": {
          "backend": { "const": "go" },
          "authority": { "const": "workflow-control" },
          "routingEpoch": { "type": "integer", "minimum": 1, "maximum": 9007199254740991 },
          "authorityBuildHash": { "type": "string", "pattern": "^[0-9a-f]{64}$" }
        }
      },
      "complete": { "type": "boolean" },
      "snapshot": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
      "nextCursor": {
        "type": ["string", "null"],
        "pattern": "^(attempt\\.[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}|(binding|diagnostic|settlement)\\.WFRUNNER-BINDING-[0-9a-f]{64})$"
      },
      "records": {
        "type": "array",
        "items": {
          "oneOf": [
            {
              "type": "object",
              "additionalProperties": false,
              "unevaluatedProperties": false,
              "required": ["key", "kind", "value"],
              "properties": {
                "key": {
                  "type": "string",
                  "pattern": "^(attempt\\.[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}|(binding|diagnostic|settlement)\\.WFRUNNER-BINDING-[0-9a-f]{64})$"
                },
                "kind": { "const": "binding" },
                "value": {
                  "type": "object",
                  "additionalProperties": false,
                  "unevaluatedProperties": false,
                  "required": [
                    "bindingId",
                    "state",
                    "stage",
                    "stageReceipt",
                    "resolution",
                    "resolutionReceipt"
                  ],
                  "properties": {
                    "bindingId": { "type": "string", "pattern": "^WFRUNNER-BINDING-[0-9a-f]{64}$" },
                    "state": {
                      "enum": [
                        "staged",
                        "resolved",
                        "runner_committed",
                        "completed",
                        "aborted",
                        "reconciliation_required"
                      ]
                    },
                    "stage": { "type": "string", "minLength": 1 },
                    "stageReceipt": { "type": "string", "minLength": 1 },
                    "resolution": { "type": ["string", "null"], "minLength": 1 },
                    "resolutionReceipt": { "type": ["string", "null"], "minLength": 1 }
                  }
                }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "unevaluatedProperties": false,
              "required": ["key", "kind", "value"],
              "properties": {
                "key": {
                  "type": "string",
                  "pattern": "^(attempt\\.[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}|(binding|diagnostic|settlement)\\.WFRUNNER-BINDING-[0-9a-f]{64})$"
                },
                "kind": { "const": "diagnostic" },
                "value": {
                  "type": "object",
                  "additionalProperties": false,
                  "unevaluatedProperties": false,
                  "required": ["bindingId", "operation", "state"],
                  "properties": {
                    "bindingId": { "type": "string", "pattern": "^WFRUNNER-BINDING-[0-9a-f]{64}$" },
                    "operation": {
                      "enum": [
                        "checkpoint_commit",
                        "resume_advance",
                        "effect_authorize",
                        "effect_complete",
                        "budget_reserve",
                        "budget_settle"
                      ]
                    },
                    "state": {
                      "enum": [
                        "staged",
                        "resolved",
                        "runner_committed",
                        "aborted",
                        "reconciliation_required"
                      ]
                    }
                  }
                }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "unevaluatedProperties": false,
              "required": ["key", "kind", "value"],
              "properties": {
                "key": {
                  "type": "string",
                  "pattern": "^(attempt\\.[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}|(binding|diagnostic|settlement)\\.WFRUNNER-BINDING-[0-9a-f]{64})$"
                },
                "kind": { "const": "settlement" },
                "value": { "type": "string", "minLength": 1 }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "unevaluatedProperties": false,
              "required": ["key", "kind", "value"],
              "properties": {
                "key": {
                  "type": "string",
                  "pattern": "^(attempt\\.[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}|(binding|diagnostic|settlement)\\.WFRUNNER-BINDING-[0-9a-f]{64})$"
                },
                "kind": { "const": "active_attempt" },
                "value": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" }
              }
            }
          ]
        }
      }
    }
  },
  "RecoveryPauseRequest": {
    "type": "object",
    "additionalProperties": false,
    "unevaluatedProperties": false,
    "required": ["schema", "workspaceId", "runId", "expectedRevision", "expectedRecordHash"],
    "properties": {
      "schema": { "const": "openslack.workflow_runner_recovery_pause.v1" },
      "workspaceId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "runId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "expectedRevision": { "type": "integer", "minimum": 1, "maximum": 9007199254740991 },
      "expectedRecordHash": { "type": "string", "pattern": "^[0-9a-f]{64}$" }
    }
  },
  "RecoveryPauseReceipt": {
    "type": "object",
    "additionalProperties": false,
    "unevaluatedProperties": false,
    "required": [
      "schema",
      "workspaceId",
      "runId",
      "expectedRevision",
      "acceptedRevision",
      "resumeGeneration",
      "priorRecordHash",
      "record",
      "recordHash",
      "committedAt"
    ],
    "properties": {
      "schema": { "const": "openslack.workflow_runner_recovery_pause_receipt.v1" },
      "workspaceId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "runId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "expectedRevision": { "type": "integer", "minimum": 1, "maximum": 9007199254740991 },
      "acceptedRevision": { "type": "integer", "minimum": 1, "maximum": 9007199254740991 },
      "resumeGeneration": { "type": "integer", "minimum": 0, "maximum": 9007199254740991 },
      "priorRecordHash": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
      "record": { "type": "string", "minLength": 1 },
      "recordHash": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
      "committedAt": {
        "type": "string",
        "format": "date-time",
        "pattern": "^\\d{4}-\\d\\d-\\d\\dT\\d\\d:\\d\\d:\\d\\d\\.\\d{3}Z$"
      }
    }
  },
  "RecoveryEvidenceV3": {
    "type": "object",
    "additionalProperties": false,
    "unevaluatedProperties": false,
    "required": [
      "schema",
      "workspaceId",
      "runId",
      "route",
      "complete",
      "snapshot",
      "nextCursor",
      "records",
      "recoveryVersion",
      "readAt"
    ],
    "properties": {
      "schema": { "const": "openslack.workflow_runner_recovery_evidence.v3" },
      "workspaceId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "runId": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" },
      "route": {
        "type": "object",
        "additionalProperties": false,
        "unevaluatedProperties": false,
        "required": ["backend", "authority", "routingEpoch", "authorityBuildHash"],
        "properties": {
          "backend": { "const": "go" },
          "authority": { "const": "workflow-control" },
          "routingEpoch": { "type": "integer", "minimum": 1, "maximum": 9007199254740991 },
          "authorityBuildHash": { "type": "string", "pattern": "^[0-9a-f]{64}$" }
        }
      },
      "complete": { "type": "boolean" },
      "snapshot": { "type": "string", "pattern": "^[0-9a-f]{64}$" },
      "nextCursor": {
        "type": ["string", "null"],
        "pattern": "^(attempt\\.[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}|(binding|diagnostic|settlement)\\.WFRUNNER-BINDING-[0-9a-f]{64})$"
      },
      "records": {
        "type": "array",
        "items": {
          "oneOf": [
            {
              "type": "object",
              "additionalProperties": false,
              "unevaluatedProperties": false,
              "required": ["key", "kind", "value"],
              "properties": {
                "key": {
                  "type": "string",
                  "pattern": "^(attempt\\.[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}|(binding|diagnostic|settlement)\\.WFRUNNER-BINDING-[0-9a-f]{64})$"
                },
                "kind": { "const": "binding" },
                "value": {
                  "type": "object",
                  "additionalProperties": false,
                  "unevaluatedProperties": false,
                  "required": [
                    "bindingId",
                    "state",
                    "stage",
                    "stageReceipt",
                    "resolution",
                    "resolutionReceipt"
                  ],
                  "properties": {
                    "bindingId": { "type": "string", "pattern": "^WFRUNNER-BINDING-[0-9a-f]{64}$" },
                    "state": {
                      "enum": [
                        "staged",
                        "resolved",
                        "runner_committed",
                        "completed",
                        "aborted",
                        "reconciliation_required"
                      ]
                    },
                    "stage": { "type": "string", "minLength": 1 },
                    "stageReceipt": { "type": "string", "minLength": 1 },
                    "resolution": { "type": ["string", "null"], "minLength": 1 },
                    "resolutionReceipt": { "type": ["string", "null"], "minLength": 1 }
                  }
                }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "unevaluatedProperties": false,
              "required": ["key", "kind", "value"],
              "properties": {
                "key": {
                  "type": "string",
                  "pattern": "^(attempt\\.[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}|(binding|diagnostic|settlement)\\.WFRUNNER-BINDING-[0-9a-f]{64})$"
                },
                "kind": { "const": "diagnostic" },
                "value": {
                  "type": "object",
                  "additionalProperties": false,
                  "unevaluatedProperties": false,
                  "required": ["bindingId", "operation", "state"],
                  "properties": {
                    "bindingId": { "type": "string", "pattern": "^WFRUNNER-BINDING-[0-9a-f]{64}$" },
                    "operation": {
                      "enum": [
                        "checkpoint_commit",
                        "resume_advance",
                        "effect_authorize",
                        "effect_complete",
                        "budget_reserve",
                        "budget_settle"
                      ]
                    },
                    "state": {
                      "enum": [
                        "staged",
                        "resolved",
                        "runner_committed",
                        "aborted",
                        "reconciliation_required"
                      ]
                    }
                  }
                }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "unevaluatedProperties": false,
              "required": ["key", "kind", "value"],
              "properties": {
                "key": {
                  "type": "string",
                  "pattern": "^(attempt\\.[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}|(binding|diagnostic|settlement)\\.WFRUNNER-BINDING-[0-9a-f]{64})$"
                },
                "kind": { "const": "settlement" },
                "value": { "type": "string", "minLength": 1 }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "unevaluatedProperties": false,
              "required": ["key", "kind", "value"],
              "properties": {
                "key": {
                  "type": "string",
                  "pattern": "^(attempt\\.[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}|(binding|diagnostic|settlement)\\.WFRUNNER-BINDING-[0-9a-f]{64})$"
                },
                "kind": { "const": "active_attempt" },
                "value": { "type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._:@-]{0,255}$" }
              }
            }
          ]
        }
      },
      "recoveryVersion": {
        "type": "string",
        "pattern": "^(?:[1-9][0-9]{0,17}|9223372036854775807|[1-8][0-9]{18}|9[0-1][0-9]{17}|92[0-1][0-9]{16}|922[0-2][0-9]{15}|9223[0-2][0-9]{14}|92233[0-6][0-9]{13}|922337[0-1][0-9]{12}|92233720[0-2][0-9]{10}|922337203[0-5][0-9]{9}|9223372036[0-7][0-9]{8}|92233720368[0-4][0-9]{7}|922337203685[0-3][0-9]{6}|9223372036854[0-6][0-9]{5}|92233720368547[0-6][0-9]{4}|922337203685477[0-4][0-9]{3}|9223372036854775[0-7][0-9]{2}|922337203685477580[0-6][0-9]{0})$"
      },
      "readAt": {
        "type": "string",
        "format": "date-time",
        "pattern": "^\\d{4}-\\d\\d-\\d\\dT\\d\\d:\\d\\d:\\d\\d\\.\\d{3}Z$"
      }
    }
  }
}
`
