# Generated by scripts/workflow-contract-families/index.ts. Do not edit.
readonly -a WORKFLOW_CONTRACT_GO_PACKAGES=(
  'authoritycontract'
  'budgetcontract'
  'runnerbindingcontract'
)

workflow_contract_dockerignore_rule_allowed() {
  case "$1" in
    '!authoritycontract/') return 0 ;;
    '!authoritycontract/*.go') return 0 ;;
    '!authoritycontract/generated/') return 0 ;;
    '!authoritycontract/generated/v2/') return 0 ;;
    '!authoritycontract/generated/v2/*.json') return 0 ;;
    '!authoritycontract/generated/v2/schemas/') return 0 ;;
    '!authoritycontract/generated/v2/schemas/*.json') return 0 ;;
    '!budgetcontract/') return 0 ;;
    '!budgetcontract/*.go') return 0 ;;
    '!budgetcontract/generated/') return 0 ;;
    '!budgetcontract/generated/v1/') return 0 ;;
    '!budgetcontract/generated/v1/*.json') return 0 ;;
    '!budgetcontract/generated/v1/schemas/') return 0 ;;
    '!budgetcontract/generated/v1/schemas/*.json') return 0 ;;
    '!runnerbindingcontract/') return 0 ;;
    '!runnerbindingcontract/*.go') return 0 ;;
    '!runnerbindingcontract/generated/') return 0 ;;
    '!runnerbindingcontract/generated/v1/') return 0 ;;
    '!runnerbindingcontract/generated/v1/*.json') return 0 ;;
    '!runnerbindingcontract/generated/v1/schemas/') return 0 ;;
    '!runnerbindingcontract/generated/v1/schemas/*.json') return 0 ;;
    *) return 1 ;;
  esac
}
