import type { PRReviewReport } from './types.js';
import { filterValidApprovals, isBotUser } from './approvals.js';
import { renderPRDecisionSummary, summarizePRDecision } from './decision-summary.js';

export function generateDoctorReport(
  report: PRReviewReport,
  codeowners: string[],
): string {
  const validApprovers = filterValidApprovals(report.reviews, report.author, report.headSha);
  const validApproverSet = new Set(validApprovers);
  const totalReviews = report.reviews.length;
  const botApprovals = report.reviews.filter(
    (r) => r.state === 'APPROVED' && isBotUser(r.user),
  );

  const checkSummary =
    report.checks.length === 0
      ? 'none'
      : report.checks.every(
          (c) => c.status === 'completed'
            && (c.conclusion === 'success' || c.conclusion === 'neutral' || c.conclusion === 'skipped'),
        )
        ? 'pass'
        : report.checks.some(
            (c) => c.conclusion && c.conclusion !== 'success' && c.conclusion !== 'neutral' && c.conclusion !== 'skipped',
          )
          ? 'fail'
          : 'pending';

  const lines: string[] = [
    '## PR Governance Doctor Report',
    '',
    `| Field | Value |`,
    `|-------|-------|`,
    `| PR | #${report.prNumber} — ${report.title} |`,
    `| Author | @${report.author} |`,
    `| State | ${report.draft ? 'Draft' : report.state} |`,
    `| Risk Zone | **${report.riskZone.toUpperCase()}** |`,
    `| Checks | ${checkSummary} |`,
    `| Reviews | ${totalReviews} total, ${validApprovers.length} valid |`,
    `| CODEOWNERS | ${codeowners.length > 0 ? codeowners.join(', ') : 'None'} |`,
    `| Valid approvers (excl. author) | ${validApprovers.length > 0 ? validApprovers.map((u) => `@${u}`).join(', ') : 'None'} |`,
    '',
    '### Changed Files',
    '',
    ...(report.changedFiles.length > 0
      ? report.changedFiles.map((f) => `- \`${f}\``)
      : ['No files changed.']),
    '',
    '### Checks',
    '',
    ...(report.checks.length > 0
      ? report.checks.map((c) => {
          const icon =
            c.conclusion === 'success'
              ? '✅'
              : c.conclusion === 'skipped'
                ? '⏭️'
                : c.conclusion === null || c.status !== 'completed'
                  ? '⏳'
                  : '❌';
          return `- ${icon} ${c.name} (${c.status}${c.conclusion ? ` / ${c.conclusion}` : ''})`;
        })
      : ['No checks found.']),
    '',
    '### Reviews',
    '',
    ...(report.reviews.length > 0
      ? report.reviews.map((r) => {
          const valid = validApproverSet.has(r.user);
          return `- ${valid ? '✅' : '⚠️'} @${r.user}: ${r.state}${valid ? ' (valid)' : ''}`;
        })
      : ['No reviews yet.']),
    ...(botApprovals.length > 0
      ? ['', `*Note: ${botApprovals.length} bot approval(s) ignored per policy.*`]
      : []),
    '',
    '### Workflow Gate',
    '',
    ...(report.workflowGate
      ? [
          `| Criterion | Status |`,
          `|-----------|--------|`,
          ...report.workflowGate.criteria.map((c) => `| ${c.name} | ${c.status}${c.detail ? ` — ${c.detail}` : ''} |`),
          '',
          `**Overall: ${report.workflowGate.overall}**`,
        ]
      : ['No workflow gate evaluated.']),
    '',
    '### Decision',
    '',
    `**${report.decision}**`,
    '',
    '### Reasons',
    '',
    report.reason,
    '',
    '### Recommendation',
    '',
    report.recommendation,
    '',
    renderPRDecisionSummary(summarizePRDecision(report, codeowners)),
    '',
    '---',
    '*Generated by OpenSlack PR Governance Doctor*',
  ];

  return lines.join('\n');
}
