import type { PRReviewReport } from './types.js';

export function generateReviewReport(report: PRReviewReport): string {
  const lines: string[] = [
    '## OpenSlack PR Review Report',
    '',
    `| Field | Value |`,
    `|-------|-------|`,
    `| PR | #${report.prNumber} — ${report.title} |`,
    `| Author | @${report.author} |`,
    `| Risk Zone | **${report.riskZone.toUpperCase()}** |`,
    `| Mergeable | ${report.mergeable ? 'Yes' : 'No / Unknown'} |`,
    `| Decision | **${report.decision}** |`,
    `| Human Approvals | ${report.humanApprovals.length > 0 ? report.humanApprovals.map((a) => `@${a.user}`).join(', ') : 'None'} |`,
    '',
    '### Changed Files',
    '',
    ...report.changedFiles.map((f) => `- \`${f}\``),
    '',
    '### Checks',
    '',
    ...report.checks.map((c) => {
      const icon =
        c.conclusion === 'success'
          ? '✅'
          : c.conclusion === 'skipped'
            ? '⏭️'
            : c.conclusion === null || c.status !== 'completed'
              ? '⏳'
              : '❌';
      return `- ${icon} ${c.name} (${c.status}${c.conclusion ? ` / ${c.conclusion}` : ''})`;
    }),
    '',
    '### Reviews',
    '',
    ...(report.reviews.length > 0
      ? report.reviews.map((r) => `- @${r.user}: ${r.state}`)
      : ['No reviews yet.']),
    '',
    '### Reason',
    '',
    report.reason,
    '',
    '### Recommendation',
    '',
    report.recommendation,
    '',
    '---',
    '*Generated by OpenSlack PR Review & Merge Steward*',
  ];

  return lines.join('\n');
}
