import { MANIFEST_VALIDATION_CODES } from './validation.js';

/**
 * Stable, machine-readable diagnostics shared by plugin authoring tools and the
 * governed host. The host remains the authorization boundary and independently
 * re-runs its Red checks; a diagnostic-free authoring report is not activation
 * evidence.
 */
export const PLUGIN_DIAGNOSTIC_CODES = Object.freeze([
  ...MANIFEST_VALIDATION_CODES,
  'PLUGIN_MANIFEST_SOURCE_INVALID',
  'PLUGIN_MANIFEST_SOURCE_OUTSIDE_ROOT',
  'PLUGIN_MANIFEST_SOURCE_SYMLINK',
  'PLUGIN_MANIFEST_NOT_FOUND',
  'PLUGIN_MANIFEST_NOT_REGULAR_FILE',
  'PLUGIN_MANIFEST_IO_FAILED',
  'PLUGIN_MANIFEST_SIZE_EXCEEDED',
  'PLUGIN_MANIFEST_FILE_CHANGED',
  'PLUGIN_MANIFEST_JSON_INVALID',
  'PLUGIN_MANIFEST_HARD_POLICY_DENIED',
  'PLUGIN_MANIFEST_VALIDATION_FAILED',
  'PLUGIN_MANIFEST_ID_MISMATCH',
  'STRICT_JSON_UTF8_INVALID',
  'STRICT_JSON_BOM_FORBIDDEN',
  'STRICT_JSON_SYNTAX_INVALID',
  'STRICT_JSON_DUPLICATE_KEY',
  'STRICT_JSON_NUMBER_NON_FINITE',
  'STRICT_JSON_DEPTH_EXCEEDED',
  'STRICT_JSON_NODE_LIMIT_EXCEEDED',
  'STRICT_JSON_STRING_LIMIT_EXCEEDED',
  'PLUGIN_HOST_LOCK_ENTRY_MISSING',
  'PLUGIN_HOST_LOCK_IDENTITY_MISMATCH',
  'PLUGIN_HOST_LOCK_SOURCE_MISMATCH',
  'PLUGIN_HOST_LOCK_HASH_MISMATCH',
  'PLUGIN_HOST_LOCK_GATE_MISMATCH',
  'PLUGIN_HOST_VERSION_INCOMPATIBLE',
  'PLUGIN_ALIAS_TARGET_FORBIDDEN',
  'PLUGIN_REGISTRY_ACTION_COLLISION',
  'PLUGIN_REGISTRY_WORKFLOW_COLLISION',
  'PLUGIN_LOCK_BYTES_INVALID',
  'PLUGIN_LOCK_TOO_LARGE',
  'PLUGIN_LOCK_NOT_OBJECT',
  'PLUGIN_LOCK_FIELD_REQUIRED',
  'PLUGIN_LOCK_FIELD_UNKNOWN',
  'PLUGIN_LOCK_FIELD_INVALID',
  'PLUGIN_LOCK_SCHEMA_UNSUPPORTED',
  'PLUGIN_LOCK_DUPLICATE_ID',
  'PLUGIN_LOCK_ORDER_INVALID',
  'PLUGIN_LOCK_SOURCE_REF_INVALID',
  'PLUGIN_LOCK_HASH_INVALID',
  'PLUGIN_LOCK_PATH_UNSAFE',
  'PLUGIN_LOCK_FILE_UNSAFE',
] as const);

export type PluginDiagnosticCode = (typeof PLUGIN_DIAGNOSTIC_CODES)[number];

export interface PluginDiagnosticFinding {
  readonly severity: 'error';
  readonly code: PluginDiagnosticCode;
  readonly path: string;
  readonly message: string;
}

const PLUGIN_DIAGNOSTIC_CODE_SET = new Set<string>(PLUGIN_DIAGNOSTIC_CODES);

export function isPluginDiagnosticCode(value: unknown): value is PluginDiagnosticCode {
  return typeof value === 'string' && PLUGIN_DIAGNOSTIC_CODE_SET.has(value);
}
